[versions]
dokka = "2.1.0"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
ktlint = "13.1.0"
kotlinTelegramBot = "6.0.7"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinTelegramBot = { module = "io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram", version.ref = "kotlinTelegramBot" }

[plugins]
dokkaPlugin = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
